# https://taskfile.dev

version: '3'

dotenv: ['.env']
output: prefixed
silent: true

vars:
  CLUSTER_NAME: kubeflow
  CONTEXT_NAME: "k3d-{{.CLUSTER_NAME}}"
  BIN_DIR: '{{.BIN_DIR | default "$HOME/.local/bin"}}'
  PATH: '{{.BIN_DIR}}:{{.PATH}}'
  KUBECTL: "kubectl --context={{.CONTEXT_NAME}}"
  KUBEAPPLY: "{{.KUBECTL}} apply"
  KUSTOMIZE: "{{.KUBECTL}} kustomize"
  KUSTOMIZEAPPLY: "{{.KUBEAPPLY}} --kustomize"
  KUBEWAIT: "{{.KUBECTL}} wait"
  KUBEWAIT_AVAIL: "{{.KUBEWAIT}} --for=condition=available"
  KUBEWAIT_READY: "{{.KUBEWAIT}} --for=condition=ready"
  KUBECREATE: "{{.KUBECTL}} create -o yaml --dry-run=client"

  TODAY: '{{ now | date "2006-01-02T15:04:05-07:00" }}'

  # Colors (ANSI-safe)
  BLACK: "\033[0;30m"
  RED: "\033[0;31m"
  GREEN: "\033[0;32m"
  YELLOW: "\033[1;33m"
  BLUE: "\033[0;34m"
  CYAN: "\033[0;36m"
  WHITE: "\033[1;37m"
  NOCOLOR: "\033[0m"

tasks:
  default:
    prefix: âš™ï¸
    cmds:
      - task -l
    silent: true

  help:
    desc: show all available tasks
    cmds:
      - echo -e "{{.BLUE}}Available Tasks:{{.NOCOLOR}}"
      - task --list

  # ------------------------------------------------------
  # Kustomize Auto-Fix
  # ------------------------------------------------------

  # ------------------------------------------------------
  # Kustomize Auto-Fix (recursive)
  # ------------------------------------------------------

  kustomize:fix:
    desc: run 'kustomize edit fix' in all directories containing a kustomization.yaml
    cmds:
      - |
        echo "ðŸ”§ Scanning for Kustomize directories..."
        find kustomize -type f -name kustomization.yaml | while read -r file; do
          dir=$(dirname "$file")
          echo "ðŸ©¹ Running 'kustomize edit fix' in $dir"
          (cd "$dir" && kustomize edit fix)
        done

  # ------------------------------------------------------
  # Setup and Dependencies
  # ------------------------------------------------------

  setup:deps:
    prefix: setup > deps
    desc: install CLI dependencies (kubectl, kustomize, k3d, yq)
    cmds:
      - mkdir -p $HOME/.local/bin

      - echo "ðŸ“¦ Installing kubectl..."
      - curl -L "https://dl.k8s.io/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl" -o "$HOME/.local/bin/kubectl"
      - chmod +x "$HOME/.local/bin/kubectl"

      - echo "ðŸ“¦ Installing kustomize..."
      - curl -L "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz" | tar -xz -C /tmp && chmod +x /tmp/kustomize && mv /tmp/kustomize $HOME/.local/bin/kustomize && rm -rf /tmp/kustomize

      - echo "ðŸ“¦ Installing k3d..."
      - curl -s "https://raw.githubusercontent.com/rancher/k3d/main/install.sh" | TAG=v${K3D_VERSION} bash

      - echo "ðŸ“¦ Installing yq..."
      - rm -f "$HOME/.local/bin/yq"
      - curl -L "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64" -o "$HOME/.local/bin/yq"
      - chmod +x "$HOME/.local/bin/yq"

  # ------------------------------------------------------
  # K3D Cluster Lifecycle
  # ------------------------------------------------------

  k3d:create:
    prefix: k3d > create
    desc: create k3d cluster
    cmds:
      - echo "ðŸš€ Creating cluster {{.CLUSTER_NAME}}..."
      - k3d cluster create --config=cluster/config.yaml

  k3d:destroy:
    prefix: k3d > destroy
    desc: destroy k3d cluster safely
    cmds:
      - |
        if k3d cluster list | grep -q {{.CLUSTER_NAME}}; then
          echo "ðŸ§¹ Deleting cluster {{.CLUSTER_NAME}}..."
          k3d cluster delete {{.CLUSTER_NAME}}
        else
          echo "Cluster {{.CLUSTER_NAME}} not found."
        fi

  k3d:recreate:
    prefix: k3d > recreate
    desc: destroy and recreate the k3d cluster
    cmds:
      - task: k3d:destroy
      - task: k3d:create

  k3d:start:
    prefix: k3d > start
    desc: start existing cluster
    cmds:
      - "k3d cluster start {{.CLUSTER_NAME}}"

  k3d:stop:
    prefix: k3d > stop
    desc: stop existing cluster
    cmds:
      - "k3d cluster stop {{.CLUSTER_NAME}}"

  k3d:test:
    prefix: k3d > test
    desc: run Kubeflow manifest validation test
    cmds:
      - task: stack:datum:preview

  # ------------------------------------------------------
  # Stack Management
  # ------------------------------------------------------

  stack:prepare:
    desc: ensure manifests directory exists
    cmds:
      - mkdir -p manifests

  stack:datum:
    prefix: stacks > datum
    desc: apply the DATUM Stack
    dir: ./kustomize
    cmds:
      - "{{.KUSTOMIZEAPPLY}} stacks/datum"

  stack:datum:preview:
    prefix: stacks > datum
    desc: render DATUM Stack manifests to ./manifests/datum.yaml
    dir: ./kustomize
    deps: [stack:prepare]
    cmds:
      - "{{.KUSTOMIZE}} stacks/datum --output=../manifests/datum.yaml"

  stack:argo:
    prefix: stacks > argo
    desc: apply the Argo Stack
    dir: ./kustomize
    cmds:
      - "{{.KUSTOMIZEAPPLY}} stacks/argo"

  stack:argo:preview:
    prefix: stacks > argo
    desc: render Argo Stack manifests to ./manifests/argo.yaml
    dir: ./kustomize
    deps: [stack:prepare]
    cmds:
      - "{{.KUSTOMIZE}} stacks/argo --output=../manifests/argo.yaml"
