apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubeflow
  namespace: kubeflow-system
spec:
  generators:
  - list:
      elements:

      ## Provides ArgoCD Application Metadata for the `datum` stack
      ##
      ##

      ## Kubeflow (applications)

      - app: admission-webhook
        folder: applications
        version: main
      - app: centraldashboard
        folder: applications
        version: main
      - app: jupyter-web-app
        folder: applications/jupyter
        version: main
      - app: notebook-controller
        folder: applications/jupyter
        version: main
      - app: katib
        folder: applications/kserve
        version: main
      - app: kserve
        folder: applications/kserve
        version: main
      - app: models-web-app
        folder: applications/kserve
        version: main
      - app: model-registry
        folder: applications
        version: main
      # - app: pipeline         // (Seaweed FS default)
      #   folder: applications
      #   version: main
      - app: profiles
        folder: applications
        version: main
      - app: pvcviewer-controller
        folder: applications
        version: main
      - app: spark
        folder: applications
        version: main
      - app: tensorboard-controller
        folder: applications/tensorboard
        version: main
      - app: tensorboard-web-app
        folder: applications/tensorboard
        version: main
      - app: training-operator
        folder: applications
        version: main
      - app: volumes-web-app
        folder: applications
        version: main

      ## Kubeflow (common)

      - app: knative-serving
        folder: common/knative
        version: main
      - app: kubeflow-namespace
        folder: common
        version: main
      - app: kubeflow-roles
        folder: common
        version: main
      - app: networkpolicies
        folder: common
        version: main
      - app: oauth2-proxy
        folder: common
        version: main
      - app: user-namespace
        folder: common
        version: main

      ## Kubeflow (experimental)

      - app: ray
        folder: experimental
        version: main
      - app: seaweedfs
        folder: experimental
        version: main

  template:
    metadata:
      name: 'kubeflow-datum'
      namespace: kubeflow-system
    spec:
      project: default
      source:
        repoURL: 'https://github.com/gccloudone-aurora/kubeflow-manifests.git'
        targetRevision: '{{version}}'
        path: kustomize/{{folder}}/{{app}}/base
      destination:
        namespace: kubeflow-system
        name: in-cluster
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
